/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'interiorOnly' : IDL.Null,
  'exteriorOnly' : IDL.Null,
  'premiumDetail' : IDL.Null,
  'motorcycleDetail' : IDL.Null,
  'standardDetail' : IDL.Null,
  'rvWash' : IDL.Null,
  'ceramicCoating' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'vehicleInfo' : IDL.Text,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'tiktok' : IDL.Text,
  'instagram' : IDL.Text,
  'phone' : IDL.Text,
});
export const ServiceInfo = IDL.Record({
  'hours' : IDL.Text,
  'area' : IDL.Text,
});
export const BookingInput = IDL.Record({
  'vehicleInfo' : IDL.Text,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllBookings' : IDL.Func([], [], []),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getServiceInfo' : IDL.Func([], [ServiceInfo], ['query']),
  'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateServiceInfo' : IDL.Func([ServiceInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'interiorOnly' : IDL.Null,
    'exteriorOnly' : IDL.Null,
    'premiumDetail' : IDL.Null,
    'motorcycleDetail' : IDL.Null,
    'standardDetail' : IDL.Null,
    'rvWash' : IDL.Null,
    'ceramicCoating' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'vehicleInfo' : IDL.Text,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'tiktok' : IDL.Text,
    'instagram' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ServiceInfo = IDL.Record({ 'hours' : IDL.Text, 'area' : IDL.Text });
  const BookingInput = IDL.Record({
    'vehicleInfo' : IDL.Text,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllBookings' : IDL.Func([], [], []),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getServiceInfo' : IDL.Func([], [ServiceInfo], ['query']),
    'getUpcomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateServiceInfo' : IDL.Func([ServiceInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };