/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'vehicleInfo' : string,
  'serviceType' : ServiceType,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'preferredDate' : string,
  'notes' : string,
  'preferredTime' : string,
  'phone' : string,
}
export interface BookingInput {
  'vehicleInfo' : string,
  'serviceType' : ServiceType,
  'name' : string,
  'email' : string,
  'preferredDate' : string,
  'notes' : string,
  'preferredTime' : string,
  'phone' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface ContactInfo {
  'tiktok' : string,
  'instagram' : string,
  'phone' : string,
}
export interface ServiceInfo { 'hours' : string, 'area' : string }
export type ServiceType = { 'interiorOnly' : null } |
  { 'exteriorOnly' : null } |
  { 'premiumDetail' : null } |
  { 'motorcycleDetail' : null } |
  { 'standardDetail' : null } |
  { 'rvWash' : null } |
  { 'ceramicCoating' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllBookings' : ActorMethod<[], undefined>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getServiceInfo' : ActorMethod<[], ServiceInfo>,
  'getUpcomingBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<[BookingInput], bigint>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateServiceInfo' : ActorMethod<[ServiceInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];